version: 2

updates:
    - package-ecosystem: "npm" # See documentation for possible values
      target-branch: "main"
      directory: "/" # Location of package manifests
      schedule:
          interval: "daily"
      groups:
        dependencies:
            applies-to: version-updates
            patterns:
                - "*"
      cooldown:
          semver-major-days: 5 # Waits 5 days before updating major versions
          semver-minor-days: 3  # Waits 3 days before updating minor versions
          semver-patch-days: 2  # Waits 2 days before updating patch versions

    - package-ecosystem: "github-actions"
      target-branch: "main"
      directory: "/.github/workflows"
      schedule:
        interval: "daily"
      groups:
        dependencies:
            applies-to: version-updates
            patterns:
                - "*"
